#!/usr/bin/env node
/**
 * Generates the site photography with Google's Nano Banana image model
 * (Gemini 2.5 Flash Image) and writes it to public/assets/images.
 *
 *   npm run images:generate              # regenerate the stand-in images only
 *   npm run images:generate -- --all     # regenerate every image
 *   npm run images:generate -- --only night_villa_hills,contact_hero
 *   npm run images:generate -- --list    # show image names and exit
 *
 * Needs GEMINI_API_KEY (or GOOGLE_API_KEY) in the environment, .env.local or .env.
 * Override the model with GEMINI_IMAGE_MODEL (e.g. a newer Nano Banana release).
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(root, "public", "assets", "images");

for (const file of [".env.local", ".env"]) {
  try {
    process.loadEnvFile(path.join(root, file));
  } catch {
    // Missing env files are fine; the key may already be in the environment.
  }
}

const apiKey = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY;
const model = process.env.GEMINI_IMAGE_MODEL || "gemini-2.5-flash-image";

const style =
  "Photorealistic editorial luxury travel photograph, shot on a full-frame camera with natural light, " +
  "soft atmospheric haze, muted earthy palette of mossy greens, warm teak browns and misty greys, " +
  "Kandy hill country, Sri Lanka. No people's faces, no text, no watermark, no logos.";

/** standIn: currently a graded stand-in derived from another photo — regenerated by default. */
const images = [
  {
    name: "homepage_hero",
    aspect: "16:9",
    prompt:
      "Wide sunset view from a secluded hilltop villa: an infinity pool on a timber deck with cushioned loungers on the right, an open teak pavilion glowing with warm lamplight, layered misty mountain ridges and a pastel peach sky on the left.",
  },
  {
    name: "about_hero_panorama",
    aspect: "16:9",
    prompt:
      "Serene panoramic landscape of mist-veiled forested hills around a still lake at dawn, soft white fog drifting between the ridges, tall lone tree in the foreground canopy, calm and meditative.",
  },
  {
    name: "contact_hero",
    aspect: "21:9",
    standIn: true,
    prompt:
      "Golden sunrise over a deep misty valley seen from a modern timber and glass villa terrace; left two-thirds is soft hazy peach sky over layered forest ridges and a distant lake, the right edge shows the dark wooden frame of the glass pavilion with a low table and plants. Bright, airy left side suitable for overlaid dark text.",
  },
  {
    name: "gallery_cta_mist",
    aspect: "21:9",
    standIn: true,
    prompt:
      "Very wide, low-contrast banner of a misty valley: two dark forested hillsides slope down from the left and right edges forming a soft V, the centre filled with pale grey fog and faint distant ridges. Desaturated, calm, cool grey tones, bright empty centre suitable for overlaid dark text.",
  },
  {
    name: "night_villa_hills",
    aspect: "3:4",
    standIn: true,
    prompt:
      "Blue-hour photograph of a two-storey hillside villa with stone base and timber balconies, every window glowing warm amber, nestled in dense dark rainforest on a steep slope under a deep blue dusk sky, stone steps leading up through the trees.",
  },
  {
    name: "villa_forest_exterior",
    aspect: "4:3",
    prompt:
      "Timber villa with a wide covered veranda raised on a hand-laid stone plinth, set in lush misty rainforest, warm lamplight inside, ferns and tropical foliage in the foreground, cloud drifting through tall trees behind.",
  },
  {
    name: "stone_bath",
    aspect: "4:3",
    prompt:
      "A carved round stone soaking tub filled with water and floating white frangipani flowers, in a private tropical garden with ferns, a small teak side table and candles, misty forest behind.",
  },
  {
    name: "open_air_pavilion",
    aspect: "4:3",
    prompt:
      "Open-air teak pavilion lounge with a high timber roof, linen sofas and a low coffee table, framing a view over misty green valleys and distant mountains.",
  },
  {
    name: "pool_mist",
    aspect: "4:3",
    prompt:
      "Infinity pool with a stone edge reflecting mist-covered mountains at soft morning light, two teak loungers at the side, framed by overhanging tropical trees.",
  },
  {
    name: "teak_bedroom",
    aspect: "4:3",
    prompt:
      "Serene master bedroom with a vaulted timber ceiling, Ceylon teak furniture, crisp cream linen on a large bed, floor-to-ceiling glass doors opening onto a misty forested valley.",
  },
  {
    name: "tea_terrace",
    aspect: "4:3",
    prompt:
      "Private timber terrace with two wooden chairs and a small round table set with a cast-iron teapot and cups of Ceylon tea, overlooking a winding river valley in golden morning mist.",
  },
  {
    name: "artisanal_breakfast",
    aspect: "4:3",
    prompt:
      "Overhead three-quarter view of a Sri Lankan breakfast spread on a rustic teak table on a veranda: hoppers, egg hoppers, sambol, curries in clay bowls, tropical fruit and tea, lush hills beyond.",
  },
  {
    name: "host_dining_ritual",
    aspect: "16:9",
    prompt:
      "Close, shallow depth-of-field shot of a private chef's Sri Lankan curry feast in black stoneware bowls on a dark wooden table with a cast-iron teapot, soft green garden bokeh behind.",
  },
  {
    name: "reclaimed_teak",
    aspect: "4:3",
    prompt:
      "Macro detail of weathered reclaimed Ceylon teak planks with deep grain and old joinery marks, a hand-carved wooden bowl in the corner, warm side light.",
  },
  {
    name: "chiseled_stone",
    aspect: "4:3",
    prompt:
      "Texture of a hand-laid dry river-stone wall with rounded grey stones, ferns and tropical leaves growing from the right side, soft diffused light.",
  },
  {
    name: "mist_mountain_ridge",
    aspect: "4:3",
    prompt:
      "Rainforest-covered ridges rising out of a sea of low white cloud, a few tall trees in the foreground on the left, soft overcast light.",
  },
];

const args = process.argv.slice(2);
if (args.includes("--list")) {
  for (const img of images) console.log(`${img.name}${img.standIn ? "  (stand-in)" : ""}`);
  process.exit(0);
}

const onlyArg = args.find((a) => a.startsWith("--only"));
const onlyValue = onlyArg?.includes("=") ? onlyArg.split("=")[1] : onlyArg ? args[args.indexOf(onlyArg) + 1] : null;
const only = onlyValue ? new Set(onlyValue.split(",").map((s) => s.trim())) : null;

const targets = images.filter((img) => (only ? only.has(img.name) : args.includes("--all") || img.standIn));

if (only) {
  const unknown = [...only].filter((n) => !images.some((img) => img.name === n));
  if (unknown.length) {
    console.error(`Unknown image name(s): ${unknown.join(", ")}. Run with --list to see valid names.`);
    process.exit(1);
  }
}

if (!apiKey) {
  console.error("GEMINI_API_KEY is not set. Add it to your environment or to .env.local, then re-run.");
  process.exit(1);
}

let sharp = null;
try {
  sharp = (await import("sharp")).default;
} catch {
  console.warn("sharp is not available; images will be saved exactly as returned by the API.");
}

async function generate(img) {
  const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`, {
    method: "POST",
    headers: { "Content-Type": "application/json", "x-goog-api-key": apiKey },
    body: JSON.stringify({
      contents: [{ parts: [{ text: `${img.prompt} ${style}` }] }],
      generationConfig: { responseModalities: ["IMAGE"], imageConfig: { aspectRatio: img.aspect } },
    }),
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}: ${(await res.text()).slice(0, 400)}`);

  const json = await res.json();
  const parts = json.candidates?.[0]?.content?.parts ?? [];
  const inline = parts.map((p) => p.inlineData ?? p.inline_data).find(Boolean);
  if (!inline?.data) {
    const reason = json.candidates?.[0]?.finishReason ?? json.promptFeedback?.blockReason ?? "no image returned";
    throw new Error(`No image in response (${reason})`);
  }

  const buffer = Buffer.from(inline.data, "base64");
  const out = path.join(outDir, `${img.name}.jpg`);
  if (sharp) {
    await sharp(buffer).jpeg({ quality: 86, mozjpeg: true }).toFile(out);
  } else {
    await writeFile(out, buffer);
  }
  return out;
}

console.log(`Model: ${model} — generating ${targets.length} image(s)\n`);
let failed = 0;
for (const img of targets) {
  process.stdout.write(`• ${img.name} (${img.aspect}) … `);
  try {
    const out = await generate(img);
    console.log(`saved ${path.relative(root, out)}`);
  } catch (err) {
    failed++;
    console.log(`FAILED\n  ${err.message}`);
  }
}
console.log(failed ? `\n${failed} image(s) failed.` : "\nDone.");
process.exit(failed ? 1 : 0);
